// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnborcilhnwptigmdchg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuYm9yY2lsaG53cHRpZ21kY2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTkxNTYsImV4cCI6MjA2OTA5NTE1Nn0.TgIX5U7oi_6PkN5Nxf17ONoglkuiu3_V27dcYfR5mt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});